<a href="https://colab.research.google.com/github/tanujashettar/NUMPY-DATA-HANDLING-STATISTICS-/blob/main/Python_file_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task-1: Arrays basics

In [ ]:
import numpy as np


In [6]:
data = np.array([12, 15, 20, 20, 25, 30, 35, 40])
print(data)



[12 15 20 20 25 30 35 40]


In [8]:
print(data.size)
print(data.dtype)
print(data.shape)

8
int64
(8,)


Task3: NumPy Statistical Functions
Using NumPy, calculate:


In [11]:
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))

24.625
22.5
83.484375
9.136978439287246


TASK–4: Conditional Data Handling

In [26]:
data = np.array([12, 15, 20, 20, 25, 30, 35, 40])
print(data)
#Display all values greater than 20
data[data > 20]

[12 15 20 20 25 30 35 40]


array([25, 30, 35, 40])

In [27]:
#Count how many values are less than 20
data[data < 20].size

2

In [29]:
#Replace values less than 20 with 20
data[data < 20] = 20
print(data)


[20 20 20 20 25 30 35 40]


TASK–5: Mini Use Case

In [38]:
import numpy as np

data = np.array([12, 15, 20, 20, 25, 30, 35, 40])
print(data)

[12 15 20 20 25 30 35 40]


In [39]:
print(np.max(data))
print(np.min(data))

40
12


In [40]:
#Count Pass Students (pass mark = 20)
passcount = np.sum(data >= 20)
print(passcount)

6


In [42]:
#Average Marks
avg = np.mean(data)
print(avg)

24.625


In [46]:
#Class Performance
if avg < 20:
    performance = "Poor"
elif avg < 30:
    performance = "Average"
else:
    performance = "Good"
print("Class Performance:", performance)


Class Performance: Average
